Added Sponsors Name
offspot/metrics pull request #116
Opened 2024-02-29 17:32 UTC by HimaTeju

## Rationale

[//]: # (Briefly explain the reason behind this change.)
Closes #115 

## Changes

[//]: # (Summarize what has changed.)
Added logo, name, and link to the website in readme.

2024-02-29 17:39 UTC, benoit74 commented
The fact that the logo is almost white is really weird:

![image](https://github.com/offspot/metrics/assets/7102089/182f4c75-fb77-4a89-af33-8e79427c4fed)

@Popolechien are we allowed to modify the logo to remove all the white padding? or is it better to simply not have any logo at all?

2024-02-29 19:11 UTC, Popolechien commented
@benoit74 Yes we can remove the padding, we added just so it would fit on the website.

2024-02-29 19:17 UTC, benoit74 requested changes
Please:
- use this version: https://skat-foundation.ch/wp-content/uploads/2023/04/logo_hirschmann_stiftung-1.jpg
- add the logo file to the source code instead of directly using the link, so that if for any reason the online file is removed the README is not broken
- simplify the phrase: `Development of this tool was made possible through a grant from [Hirschmann Stiftung](https://www.hirschmann-stiftung.ch/)` (no more bold, no more duplicate reference to the company)

2024-03-01 03:05 UTC, HimaTeju commented
@benoit74 I am thinking of gathering all the images used into a separate folder for better organization since currently, the images are scattered. What's your opinion on this?

2024-03-01 06:18 UTC, benoit74 commented
> I am thinking of gathering all the images used into a separate folder for better organization since currently, the images are scattered. What's your opinion on this?

I agree there is maybe already too much things on the root folder. Maybe move all markdown (except README.md and CHANGELOG.md) to a `docs` folder + all images to a `docs/images` folder ? This means the logo will be a bit far away from the README.md but we can live with it.

2024-03-04 09:29 UTC, benoit74 commented
Is this now ready for new review?

2024-03-04 10:52 UTC, HimaTeju commented
@benoit74 I have made the necessary changes as you said. I have also used the new relative paths of the docs and images but the readme file is broken. It is not redirecting to the required docs/images.

2024-03-06 06:29 UTC, HimaTeju commented
@benoit74 PR is ready for the new review!

2024-03-07 09:16 UTC, benoit74 requested changes
Still not OK, it looks like you did not tested your modifications that much (quite straightforward to see the issues mentioned, just opening https://github.com/HimaTeju/metrics/blob/Add-Sponsor-to-readme/docs/architecture_data.md shows that image is broken)

2024-03-07 09:16 UTC, benoit74 commented on docs/architecture_data.md
> +![Data architecture](docs/images/architecture_data.excalidraw.png)
Nope, this leads to `docs/docs/images/architecture_data.excalidraw.png` which does not exists. We are already in the `docs` subfolder so should be `images/architecture_data.excalidraw.png`

2024-03-07 09:16 UTC, benoit74 commented on docs/architecture_technical.md
> +![Technical architecture](docs/images/architecture_technical.excalidraw.png)
Idem

2024-03-07 09:16 UTC, benoit74 commented on docs/database.md
> +![Indicators record](docs/images/database_indicator_record.excalidraw.png)
Idem

2024-03-07 09:16 UTC, benoit74 commented on docs/database.md
> +![Indicators state](docs/images/database_indicator_state.excalidraw.png)
Idem

2024-03-07 09:16 UTC, benoit74 commented on docs/database.md
> +![KPI](docs/images/database_kpi.excalidraw.png)
Idem

2024-03-08 04:16 UTC, HimaTeju commented on docs/database.md
> +![KPI](docs/images/database_kpi.excalidraw.png)
Shall I rename this PR? This PR is doing more than just "adding sponsors name"

2024-03-08 08:39 UTC, benoit74 approved these changes
LGTM

Please update PR title and first comment as you suggested (feel free to do without asking next time, PR title and first comment should represent the final content of the PR as much as possible). 

I will merge anyway, you can still edit the PR title and first comment after the merge.

2024-03-18 08:47 UTC, merged