First steps: global design + backend minimal structure
offspot/metrics pull request #2
Opened 2023-05-26 12:51 UTC by benoit74

## Changes
- First documentation about global design (including last discussions of this morning)
- Minimal backend structure

2023-05-26 14:26 UTC, rgaudin commented on .gitignore
> +# Byte-compiled / optimized / DLL files
Can you use https://www.toptal.com/developers/gitignore/api/python,macos,linux instead?

2023-05-26 14:50 UTC, rgaudin requested changes
Couple of suggestions but this looks all good already

2023-05-26 14:50 UTC, rgaudin commented on backend/Dockerfile
> +COPY src/ /tmp/src
Either we install the package (`pip install /src`) or we run it uninstalled (just copied in `/src`) but not both.

2023-05-26 14:50 UTC, rgaudin commented on backend/setup.py
> +    print("Please install `toml` to use setup.py")
`raise EnvironmentError()` would be appropriate

2023-05-26 14:50 UTC, rgaudin commented on backend/setup.py
> +        "Programming Language :: Python :: 3.10",
Adjust the classifiers. We're targeting 3.11

2023-05-26 14:50 UTC, rgaudin commented on backend/setup.py
> +    python_requires=">=3.8",
Let's require 3.11 for the fun of it ; we can still lower it later if required. But this is typically the kind of project we have total control over deployment and can thus use the latest features with

2023-05-26 14:50 UTC, rgaudin commented on dev/backend-tools-tests/Dockerfile
> +FROM python:3.10-slim
```suggestion
FROM python:3.11-slim
```

2023-05-26 14:50 UTC, rgaudin commented on .github/workflows/qa.yml
> +      - name: Backend - Install dependencies
You can either create different jobs that would run in parallel and independent of one another or just use the invoke task that would be very similar (albeit a single check instead of the three… but we could have individual tasks as well)

2023-06-01 05:52 UTC, benoit74 commented on .gitignore
> +# Byte-compiled / optimized / DLL files
Yep, I added a bit more indeed to also cover sqlite files + visual studio code + pycharm

2023-06-01 06:00 UTC, benoit74 commented on backend/Dockerfile
> +COPY src/ /tmp/src
But how do I make the `src` folder available in the image ? this is the intent of the `COPY`, and as far as I understood (I copied these files from `openzim/cms`, this is why we copy these files to `/tmp`, then install them with `setup.py`, and then remove the `/tmp` folder

2023-06-01 06:58 UTC, benoit74 commented on backend/Dockerfile
> +CMD ["uvicorn", "backend.entrypoint:app", "--host", "0.0.0.0", "--port", "80", "--reload"]
We could, but tasks.py is not kept in the final image for now

I could keep it as well, but I see little benefit, since I will have to also add the `--host` and `--port` custom args.

WDYT?

2023-06-01 07:08 UTC, benoit74 commented on .github/workflows/ci.yml
> +          PYTHONPATH=src pytest tests/unit
Yep, could you set the secret `CODECOV_TOKEN` in the repo please ? (or hand it over to me)

2023-06-01 07:14 UTC, benoit74 commented on .github/workflows/qa.yml
> +      - name: Backend - Install dependencies
I don't get it, for what do you consider that we might have different jobs? are you speaking about merging `qa` and `ci` workflows into a single one with two jobs (or three, one which will run first to install dependencies and two in parallel to check QA and run tests) ? If yes, I'm ok with it, it makes sense.

2023-06-01 07:17 UTC, benoit74 commented
> ❗ Your organization is not using the GitHub App Integration. As a result you may experience degraded service beginning May 15th. Please [install the Github App Integration](https://github.com/apps/codecov) for your organization. [Read more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=offspot).

@rgaudin looks like we need to do something on this at the org level

2023-06-01 07:21 UTC, benoit74 commented on .github/workflows/ci.yml
> +          PYTHONPATH=src pytest tests/unit
Looks like it finally worked without it ... I don't get what happened when it first failed ... Should we still set it or simply remove the secret from the step since it is useless ?

2023-06-01 08:04 UTC, rgaudin approved these changes
Great. Please look at inline comments (tomlib in particular) and fix ; then please go ahead and merge.

2023-06-01 13:26 UTC, merged