Parse timestamp in reverse proxy logs + make log conversion logic more generic / modular
offspot/metrics pull request #31
Opened 2023-11-07 15:20 UTC by benoit74

## Rationale
- for some inputs (for usage data indeed, coming next), we will need to have access to the timestamp where the action occurred
- logic generating inputs from log lines was too coupled to Caddy + not enough generic to easily accomodates new kind of packages / generate new kind of inputs

## Changes
- new `InputWithTime` input (not necessarily coupled to a timestamp coming from a Caddy log, typically here we use it for the `ClockTickInput` where timestamp comes from the system clock)
- adapations of `ClockTickInput` to use this new generic class
- qqq

2023-11-08 10:27 UTC, rgaudin requested changes
Good ; compiled regex have better performances

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/input_generator.py
> +        match = re.match(r"^/content/(?P<zim>.+?)(?P<item>/.*)?$", log.uri)
use a compiled regexp

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/input_generator.py
> +        item = match.group("item")
`path` seems better suited, no ?

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/input_generator.py
> +                or "epub" in log.content_type
I know it was there before: have you discussed this with @Popolechien? The fact that we consider epub and pdf files as items but no other file type.

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/inputs/input.py
> +class InputWithTime(Input):
```suggestion
class TimedInput(Input):
```

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/reverse_proxy_config.py
> +            match_viewer = re.match(r"^//.*?/viewer#(?P<zim_name>.*)$", url)
Use compiled regex as well

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +            return ProcessingResult(inputs=[], warning="Unexpected log level")
Is this really a _warning_? Are we gonna do anything with this information? JSON parsing failures are important warning for instance and generally unexpected but INFO log levels are normal and just not of interest to this piece of code. Same applies to `!= "handled request"`

2023-11-08 10:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +        log_data = LogData(
You may want to `delete line` after this as it duplicates all the needed data. We have a lot of structures and while it improves maintenance and all of them are seemingly insignificant, I'm afraid that many a little makes a mickle

2023-11-09 07:54 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/input_generator.py
> +                or "epub" in log.content_type
No it has not (yet) been discussed. I agree this needs to be done, I tracked this in https://github.com/offspot/metrics/issues/33 so we can move forward with this PR.

2023-11-09 08:02 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +            return ProcessingResult(inputs=[], warning="Unexpected log level")
For now, all these warnings are used only for tests, where they are really important to ensure that when we test something that should generate no inputs it does so for the good reason and not just because something else failed (e.g. the JSON was not valid, it happened to me many times ...)

In the future, I don't expect to do much about it. Maybe we log an error in case of JSON parsing failures. But I don't expect it will happen in reality. Or we could count the failures and log only once there are too many. Honestly I don't know what we should do about it for now, I just wanted to check tests are ok so far.

2023-11-09 08:06 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +        log_data = LogData(
I did it even a bit earlier (just after parsing JSON)

2023-11-09 08:07 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +            return ProcessingResult(inputs=[], warning="Unexpected log level")
OK ; as long as we don't fill logs with log from others 😄

2023-11-09 08:31 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +            return ProcessingResult(inputs=[], warning="Unexpected log level")
This is my concern indeed, especially since we probably will never have access to these logs 👍

2023-11-09 08:46 UTC, rgaudin approved these changes
👍

2023-11-09 08:47 UTC, merged