Add usage related stuff + fix popularity related stuff
offspot/metrics pull request #35
Opened 2023-11-10 08:46 UTC by benoit74

## Rationale

Fix #32 
#33 is almost fixed but there is still an open question in the issue which needs to be tackled before closing
Fix #34 

NOTA: some changes most probably broke the UI (changes in KPI 2001 and 2002 data structures), but since the UI will be completely revamped anyway, I do not lost my time fixing this for now, we can live with this until I restart working on the UI.

## Changes
- create a new `UsageRecorder` to count active slots of 10 minutes during which an input has been received
- create a n

2023-11-16 12:19 UTC, benoit74 commented
@rgaudin did you already start reviewing this PR or may I push a new commit? (almost negligible change, but still something you might have already spotted / might confuse you)

2023-11-16 12:55 UTC, rgaudin commented
Haven't started ; please do

2023-11-17 09:43 UTC, benoit74 commented
Ready again for review

2023-11-23 14:46 UTC, rgaudin requested changes
Thank you! 
Wise renaming while it's still doable 😄

What's the storage impact of this new generic PackageRequest?

2023-11-23 14:46 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +    def _format_minutes(self, minutes: int) -> str:
This could be a static method

2023-11-23 14:46 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +        """Processing an input consists in updating active starts list"""
This is not a helpful docstring. This method does a lot of things with several variables and conditions. Getting a sense of its objective is not trivial. It should be explained

2023-11-23 14:46 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/kpis/__init__.py
> +from offspot_metrics_backend.business.kpis.kpi import Kpi
same comments as for indicators

2023-11-23 14:46 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/kpis/total_usage.py
> +            .limit(10)
Maybe this could be a class variable for better exposure/maintenance ; since it's not in the KPI name

2023-11-23 14:46 UTC, rgaudin commented on backend/tests/unit/business/indicators/test_recorder.py
> +def get_timed_input(minutes: int = 0, seconds: int = 0) -> TimedInput:
Can you make it (and `START_TIME`) fixtures so their role is clear? Both are important since we assert static values on those in the tests

2023-11-23 14:46 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +                raise TooWideUsageError(
I don't see this being handled (except in tests). What's the use case for it to raise and what's the consequence for the running app?

2023-11-23 14:46 UTC, rgaudin commented on backend/tests/unit/business/kpis/test_total_usage.py
> +CONTENT_USAGE_DURATION_VALUE_AS_OBJECT_1 = TotalUsageValue(
Same comment, fixtures provides meaning

2023-11-23 14:46 UTC, rgaudin commented on backend/tests/unit/business/test_log_converter.py
> +    assert set(result.inputs) == set(expected_inputs)
Out of curiosity, why?

2023-11-23 15:07 UTC, benoit74 commented on backend/tests/unit/business/test_log_converter.py
> +    assert set(result.inputs) == set(expected_inputs)
Because when multiple inputs are generated for the same log line, order of inputs is not relevant. 
Do you mean that the `converter.process` should return a set as well (your remark makes me think this is probably true)?

2023-11-23 15:15 UTC, rgaudin commented on backend/tests/unit/business/test_log_converter.py
> +    assert set(result.inputs) == set(expected_inputs)
No. I'm just suspicious when a test is changed without explanation 😅. Can you add a comment to mention that both lists contains the same items but potentially in different orders?

2023-11-23 16:05 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/indicators/__init__.py
> +ALL_INDICATORS: list[Indicator] = [
Makes sense (even if I agree that current usage is limited)

2023-11-23 16:13 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +        if not isinstance(input_, TimedInput):
This is not really common, the other recorder we have currently (`IntCounterRecorder`) accepts any kind of input. Maybe we will at some point provide a list of accepted input types per recorder, but for now I do not see a real benefit (especially in terms of readability where this is already not always easy to navigate all these classes)

2023-11-24 07:17 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +    max_active_intervals = 6
See inline comment

2023-11-24 07:17 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +    max_time_range = 62
See inline comment

2023-11-24 07:34 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/indicators/recorder.py
> +                raise TooWideUsageError(
The fact that it is not being handled is a mistake. It is already covered in my "dev" branch but I'm waiting for this PR to finish to submit it. I realized I had many try...except logic which were missing.

The use case to raise is a delay in the processing logic which causes a log line to be assigned to a wrong period.

For simplicity, I assumed early in the design that the system will process only one period at a time, and we won't receive log lines which are not from the current period. However, this could happen (due to delays in the processing logic) and while this is not really a problem for other indicators (we will just count visits or other stuff like that in the wrong period, which is not really a big issue since the visit occurred anyway), it is a problem here were we need to find how many slots of 10 minutes have been active during the period. We do not want to finish with 8 slots of 10 minutes marked as active during a 60 minutes period ^^

What will happen is that this exception will be trapped a bit above in the processor logic and the processing will continue with other indicators.

2023-11-24 07:37 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/kpis/total_usage.py
> +            .limit(10)
Good point, I have other magic values like that I could move to a class variable.

2023-11-24 08:21 UTC, benoit74 commented on backend/tests/unit/business/kpis/test_total_usage.py
> +CONTENT_USAGE_DURATION_VALUE_AS_OBJECT_1 = TotalUsageValue(
Done

2023-11-24 08:23 UTC, benoit74 commented on backend/tests/unit/business/indicators/test_recorder.py
> +def get_timed_input(minutes: int = 0, seconds: int = 0) -> TimedInput:
Done

2023-11-24 08:30 UTC, benoit74 commented
> What's the storage impact of this new generic PackageRequest?

Inputs are not stored, so there is 0 impact on storage. There is a computing impact since these inputs will have to be processed, but since most indicators do not process this kind of inputs (only `TotalUsageOverall` and `TotalUsageByPackage` does), I expect that impact will be limited. Most indicators will just say "I don't mind about this kind of input, next!". And I hope that `TotalUsage` indicators will not consume much resources (but this has to be confirmed in perf tests).

2023-11-24 08:38 UTC, rgaudin approved these changes
Thank you ; those comments are really helpful

2023-11-24 08:39 UTC, merged