Backend: make processing logic much more resilient
offspot/metrics pull request #39
Opened 2023-11-24 13:26 UTC by benoit74

## Rationale
- Fix #37 
- Small enhancements

## Changes

[//]: # (Summarize what has changed.)

2023-11-27 10:08 UTC, rgaudin requested changes
Thank you ;

Please comply with our convention of exception name (`exc`).

Can you explain what why all those try blocks are not tested? Given how well this project is tested, I'm wondering if those are places tested elsewhere or if that's things you don't mind not being tested…

Log level should be configurable

Not a big fan of having multiple locations with timers that are somewhat identical but I think it's good enough for now. If we get additional stuff on that sync we maybe rework it

2023-11-27 10:08 UTC, rgaudin commented on backend/src/offspot_metrics_backend/main.py
> +                _, now_datetime = Period.now()
Isn't this a namedtuple now so that you don't have to do this?

2023-11-27 10:08 UTC, rgaudin commented on backend/src/offspot_metrics_backend/main.py
> +        We do not what / need something precise here because we want to let
typo ; it's not understandable

2023-11-27 15:17 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +            )  # pragma: no cover
It is the responsibility of the image user to mount a persistent folder somewhere in the container and use it as data folder for logwatcher. This folder is very important and must be persistent across executions, so I prefer not create it silently in a wrong location which will be deleted once the container stops.

For now, it's docker-compose who mount this folder. Once this will be integrated into the offspot, I assume the same will happen.

2023-11-27 15:33 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +                except Exception as ex:  # pragma: no cover
Well note for exception variable name.

Regarding coverage, I don't mind to spend some time to increase coverage / remove these pragma (some of them I'm not totally proud of). 

I assumed these tests are so low level that they are hard to make and / or might be broken as soon as we change something in the implementation (and hence mostly useless).

2023-11-27 15:34 UTC, benoit74 commented on backend/src/offspot_metrics_backend/main.py
> +                _, now_datetime = Period.now()
Indeed, I will change this

2023-11-28 08:02 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +                except Exception as ex:  # pragma: no cover
Setup related issues are the most annoying in offspot because there can be extensive delays between change in code and deployment and deployment can be spread into several projects… and it's only tested after configuring an image, building it, flashing it and running on the device.

With several devs involved now and the will to strengthen the product, we should maybe discuss live how we would like to automate some of the tests on the final product.

I an resolving this as this is an async discussion

2023-11-30 13:30 UTC, benoit74 commented
> Please comply with our convention of exception name (exc).

Done

> Can_ you explain what why all those try blocks are not tested? Given how well this project is tested, I'm wondering if those are places tested elsewhere or if that's things you don't mind not being tested…

Discussed in comment

> Log level should be configurable

Separate issue has been opened #40 

> Not a big fan of having multiple locations with timers that are somewhat identical but I think it's good enough for now. If we get additional stuff on that sync we maybe rework it

We will have less timers indeed once #41 is implemented

2023-11-30 13:31 UTC, benoit74 commented
I forgot to push and check CI status before requesting review, sorry ...

2023-11-30 13:32 UTC, benoit74 commented
Commits pushed and CI OK

2023-12-01 08:00 UTC, rgaudin approved these changes
Thank you!

2023-12-01 08:00 UTC, merged

2023-12-01 08:38 UTC, benoit74 commented on backend/tests/unit/business/test_log_watcher.py
> +        # we will try to create and move the file so fast that it won't be possible
This could probably have been an alternative, let's keep this in mind should this test become too unstable.