Business logic continued
offspot/metrics pull request #4
Opened 2023-06-15 14:29 UTC by benoit74

## Rationale

This is a part of https://github.com/offspot/metrics/issues/1

This PR focuses on the implementation of metrics business logic (almost complete now)

## Changes

- DB model for indicators and kpis
- store indicators in DB (including refresh for use at application restart)
- implement KPIs + store in DB (including refresh for use at application restart)
- do not use `asyncio` to access DB anymore (too complex / useless for now)
- use `pyright` instead of `mypy` for typing checking, less false-positiv and no false-negativ in current codebase
- fix invoke `tasks` that were not working / not adapted
- fix `dev/README.md` accordingly
- implement real input + indicator + KPI (instead of abstract ones)
- create a mini simulator, simulating from inputs processing to KPI calculations

2023-07-13 18:26 UTC, rgaudin requested changes
Thank you; this is too big of a PR to review. Let's try to do smaller ones in the future 😅

There are a lot of pieces with many connections between them. I'd really benefited from a Schema describing it all. I understand schema is doc and doc gets left out as code evolves, making it useless. WDYT? Should we try to do a v1 schema still?

2023-07-13 18:26 UTC, rgaudin commented on backend/tests/unit/business/indicators/test_indicators.py
>      records = list(total_indicator.get_records())
If it's easy, readable and won't be reused, spare the extra var.

2023-07-13 18:26 UTC, rgaudin commented on backend/tests/unit/business/indicators/test_indicators.py
> +    for data in datas:
expand for explicitness

2023-07-13 18:26 UTC, rgaudin commented on backend/src/simulator.py
> +        step += 1
```py
for step in range(nbsteps + 1):
    ....
```
replaces the init counter on line 153, the while and the increment

2023-07-13 18:26 UTC, rgaudin commented on backend/src/simulator.py
> +def rand_sim_get_content() -> str:
```suggestion
def get_random_content_from_sim() -> str:
```

2023-07-13 18:26 UTC, rgaudin commented on backend/src/simulator.py
> +def rand_sim_get_object(content: str) -> str:
```suggestion
def get_random_object_from_sim(content: str) -> str:
```

2023-07-13 18:26 UTC, rgaudin commented on backend/src/simulator.py
> +    if random.randint(0, 3) == 3:
A comment explaining the goal of this (hard to read it twice to understand)

2023-07-13 18:26 UTC, rgaudin commented on backend/src/simulator_expected_res.txt
> +sqlite> SELECT * FROM kpi ORDER BY kpi_id, kind, period;
I don't think this should be committed; or in `dev/` maybe

2023-07-13 18:26 UTC, rgaudin commented on backend/src/backend/business/kpis/kpi.py
> +    ) -> str:
I suppose you've thought this through (I haven't): why returning string values?
I haven't looked at the UI PR yet which may answers this…
If we need flexibility because each KPI is unique, then all this inheritance comes in handy.
But using `str` as API seems like a downward alignment.

2023-07-13 18:27 UTC, rgaudin requested changes
Thank you; this is too big of a PR to review. Let's try to do smaller ones in the future 😅

There are a lot of pieces with many connections between them. I'd really benefited from a Schema describing it all. I understand schema is doc and doc gets left out as code evolves, making it useless. WDYT? Should we try to do a v1 schema still?

2023-07-14 08:18 UTC, benoit74 commented on backend/pyproject.toml
> +    "ipykernel >=6.23,<6.24",
I use it to test some code, e.g. to write some sqlachemy queries and check they work as intended. You have a test notebook at `backend/src/tests.ipynb`
This is only a dev dependency.

2023-07-14 08:37 UTC, benoit74 commented on backend/pyproject.toml
> +    "pyright >=1.1,<1.2"
I find this wrapper easier to use than an npm dependency.
With this wrapper, pyright is managed as all other QA dependencies, and especially installed properly in venv.

2023-07-14 08:41 UTC, rgaudin commented on backend/pyproject.toml
> +    "pyright >=1.1,<1.2"
Let's have this discussion in the dedicated ticket

2023-07-14 13:22 UTC, benoit74 commented on backend/pyproject.toml
> +    "fastapi-pagination>=0.12,<0.13",
I will treat it in a separate PR while working on https://github.com/offspot/metrics/issues/15 (in order to try to keep this PR "simple" + not duplicate effort)

2023-07-14 13:34 UTC, benoit74 commented on backend/src/backend/business/kpis/kpi.py
> +    ) -> str:
The UI PR does not answers this.

The reasoning is:
- I prefer to have only one datatype for storing this value in DB
- Real type is largely unknown and might vary from one KPI to the next one (we might have single int value, arrays of string, complex object represented as dict[str, Any], ...)
- The KPI is responsible to serialize its value to this string
- The UI will known how to convert this value to real value (depending on which KPI it is handling)

2023-07-14 13:40 UTC, benoit74 commented on backend/src/backend/business/indicators/indicator.py
> +    unique_id = 0  # this ID is unique to each kind of indicator
Numeric IDs are smaller to store in DB than UUIDs or string + they are not sensitive to renaming of the class or the KPI (because names are always hard ...).

I tend to believe we will have to rename stuff significantly and I do want to have to manage DB updates following a name change.

_kinds of indicators_ are represented by the various classes we have. For now we have two kinds of indicators (not including dummy / test ones): `ContentHomeVisit` and `ContentObjectVisit`

I also feel this is a bit weird, but I do not find satisfaction in any other alternative.

2023-07-17 11:15 UTC, benoit74 commented
@rgaudin I pushed more documentation. 
Feedback welcomed, I don't know if this is sufficient to answer your interrogations or completely useless. 
I'm available to discuss this live, so that I get a better understanding of what is difficult to understand.
Unfortunately, there is also some code which is missing in this PR and has been created only in the next one which might help a bit to understand more easily I believe (for instance the code which transforms logs into inputs).

2023-07-17 18:37 UTC, rgaudin commented on backend/src/backend/business/indicators/indicator.py
> +    unique_id = 0  # this ID is unique to each kind of indicator
OK, Maybe we can later categorize (or distinguish KPI/Indicator) some using ranges if it gets confusing. With 255 values on a byte, there's plenty of choice

2023-07-17 18:39 UTC, rgaudin commented on backend/src/backend/business/kpis/kpi.py
> +    ) -> str:
> I prefer to have only one datatype for storing this value in DB

Well that's serialization. You can certainly store it as a string but there's no relation as to how the KPI renders its value.

> Real type is largely unknown and might vary from one KPI to the next one

Absolutely. One KPI to the next… that's why you have independent sub-classes for each.

> The UI will known how to convert this value to real value (depending on which KPI it is handling)

That's exactly the problem. You're creating this whole abstract scheme but KPIs can't be used without the UI or they need to re-implement parsing and checking.
A KPI should be able to return its native value, regardless of how it's stored. This would allow type checking and tests to work for you.

2023-07-17 18:41 UTC, rgaudin requested changes
Documentation is great ; thank you. I'm glad I got it all understood.
I think it's a great addition because it provides the big picture in a minute instead of browsing many files.

2023-07-19 07:07 UTC, benoit74 commented on backend/src/backend/business/kpis/kpi.py
> +    ) -> str:
OK, LGTM.

2023-07-20 06:45 UTC, benoit74 commented on backend/src/backend/business/indicators/holder.py
> +T = TypeVar("T")
What do you mean by being explicit? `Holder` class is never used directly, it is only `Record` and `State` that are used. Do you mean that you would prefer that I specify that `T` is only `str|int` ?

2023-07-20 06:49 UTC, benoit74 commented on backend/src/backend/business/indicators/recorder.py
>      def get_value(self) -> int:
Agreed, except that it looks like `@abc.abstractproperty` is deprecated, we can / must use `@abc.abstractmethod` and `@property` instead.
https://docs.python.org/3/library/abc.html#abc.abstractproperty

2023-07-20 06:59 UTC, benoit74 commented on backend/src/backend/business/kpis/processor.py
> +class Timestamps:
Agreed + this has nothing to do in this file, I moved this code to the `Period` class (which in addition removes one parameter)

2023-07-20 07:02 UTC, benoit74 commented on backend/src/backend/business/kpis/kpi.py
> +        self, agg_kind: str, start_ts: int, stop_ts: int, session: Session
It comes from the fact that `agg_kind` and `agg_value` are columns of a KPI record in DB and we need to make a distinction between both.
Would `horizon` be better?

2023-07-20 07:18 UTC, benoit74 commented on backend/src/backend/business/indicators/processor.py
> +        """Process a clock tick"""
I removed this parameter, it was only used in tests and made little sense indeed.

2023-07-20 08:44 UTC, benoit74 commented on backend/src/backend/business/period.py
> +        self.year = dt.year
There were two reasons in my mind:
- this makes it possible to say "we are still in the same period" more obvious
- this is (mostly indeed) what we will store in DB

I now realize this might not be that optimal. I tried the subclass approach but failed with all kinds of strange issues, probably linked to the fact that it is an immutable class. I now simply store and use the datetime.

2023-07-20 09:13 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    weekday: Mapped[int]
See below, I would say no indeed.

2023-07-20 09:14 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    timestamp: Mapped[int]
It is a duplicate. It is the Unix timestamp. 

We need this to make Kpi computations easier, because it is way easier to select all periods from a given timestamp to a given timestamp rather than use year/month/day/hour.

But your point is valid, I should probably keep only this value and remove all others since they are not used (at least for now, and we will always be able to add them afterwards if needed)

WDYT?

2023-07-20 09:15 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    id: Mapped[int] = mapped_column(init=False, primary_key=True)
Then we probably do not even need to store periods in DB, indeed this makes sense.

2023-07-20 12:37 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    def to_values(self) -> DimensionsValues:
Your first approach does not pass `pyright` checks (it complains that values might by None while we expect them not to be). This is why I had to go the uggly way.

Your second approach is more fragile from my understanding, because should value1 be None and value2 be set, then value2 would be transferred as value1, which is a problem.

I reimplemented DimensionValue as a dataclass, so no need for this ugly code anymore :)

2023-07-20 12:39 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    """An indicator temporary state
Yes, I did so for performance reasons. 

Indicator states are committed (create/update/delete) to DB every minute so I prefer to have a standalone table with few rows inside. 

Indicator records are created and not modified until deletion, and they are manipulated only once per hour.

2023-07-20 13:04 UTC, benoit74 commented on backend/src/backend/db/persister.py
> +            session.add(dbPeriod)
You mean, in a documentation Markdown?

2023-07-20 13:11 UTC, benoit74 commented on backend/src/backend/db/persister.py
> +    def get_last_current_period(cls, session: Session) -> Optional[PeriodBiz]:
I renamed it `get_last_period`, `current` had no meaning.

2023-07-20 13:22 UTC, benoit74 commented on backend/src/backend/business/indicators/processor.py
> +        self.process_tick(now=now, session=session)
No post-processing because KPI computation is not yet done and some indicators that would have to be deleted might still be useful.

I decided to not perform KPI or cleanup at this stage to simplify stuff. It will be done in at most 1 hour in any case. 

Processing the tick in the indicator is mandatory to transfer pending state as a record if time has passed since the last shutdown.

2023-07-20 13:31 UTC, benoit74 commented on backend/src/backend/business/indicators/content_visit.py
> +        input = cast(ContentObjectVisitInput, input)
Should I rename the function parameter as well or just the internal variable?

2023-07-20 13:33 UTC, benoit74 commented on backend/src/backend/business/kpis/content_popularity.py
> +        return dumps(list(session.execute(query).scalars()))
This is part of the other discussion on why I used `str` instead of a real class.

2023-07-20 13:50 UTC, benoit74 commented on backend/src/backend/business/kpis/content_popularity.py
> +    unique_id = 1
I've decided that indicator IDs must be in the range 1001 to 1999 (1000 is the default value that must never be seen in DB) and KPIs 2001 to 2999.

I've added a bit of documentation on this, I will update this documentation in the "frontend PR" where I have some stuff pending regarding to which list we must add all indicators / KPIs classes.

2023-07-20 14:15 UTC, benoit74 commented
@rgaudin: I've done a first pass on your review ; codebase is now ready to have a new feedback, especially on conversations I've left open that need is approval or decision or more information.
This was indeed very big.

2023-07-21 10:37 UTC, rgaudin commented on backend/src/backend/business/kpis/kpi.py
> +        self, agg_kind: str, start_ts: int, stop_ts: int, session: Session
I don't think so 😅

2023-07-21 12:15 UTC, rgaudin commented on backend/src/backend/db/models.py
> +    timestamp: Mapped[int]
I agree

2023-07-21 12:15 UTC, rgaudin commented on backend/src/backend/db/models.py
> +    id: Mapped[int] = mapped_column(init=False, primary_key=True)
Indeed

2023-07-21 12:17 UTC, rgaudin commented on backend/src/backend/db/models.py
> +    def to_values(self) -> DimensionsValues:
> Your second approach is more fragile from my understanding, because should value1 be None and value2 be set, then value2 would be transferred as value1, which is a problem.

No, if value1 is None, it breaks out.


> I reimplemented DimensionValue as a dataclass, so no need for this ugly code anymore :)

Good then

2023-07-21 12:22 UTC, rgaudin commented on backend/src/backend/db/persister.py
> +            session.add(dbPeriod)
No, in code comments somewhere. One has to understand the session lifecycle: what data is inserted/deleted and when is this committed? Probably on the code calling this one

2023-07-21 12:40 UTC, rgaudin commented on backend/src/backend/business/indicators/processor.py
> +        self.process_tick(now=now, session=session)
OK

2023-07-21 12:41 UTC, rgaudin commented on backend/src/backend/business/indicators/content_visit.py
> +        input = cast(ContentObjectVisitInput, input)
If you don't do both, you're still reassigning a builtin

2023-07-21 13:58 UTC, rgaudin commented on backend/src/backend/business/kpis/content_popularity.py
> +    unique_id = 1
OK, so 2b per value 👍

2023-07-21 14:12 UTC, rgaudin requested changes
Great! I think we're almost ready to merge

2023-07-21 14:12 UTC, rgaudin commented on backend/src/backend/business/agg_kind.py
> +    D = "D"
Point of the enum is to be able to be explicit on the variable while having a short DB impact. `AggKind.DAY`

2023-07-21 14:12 UTC, rgaudin commented on backend/src/backend/business/indicators/content_visit.py
>      def get_dimensions_values(self, input: Input) -> DimensionsValues:
As mentioned somewhere ; it's still reassigned (automatically though).

2023-07-24 05:49 UTC, benoit74 commented on backend/src/backend/business/indicators/holder.py
> +T = TypeVar("T")
I'm sorry, I don't get how you would write it, you need `T` to let the system know that the type of `value` is the one that has been used in the `Generic[T]`. The single letter is issued from official `typing` documentation.

2023-07-24 05:57 UTC, benoit74 commented on backend/src/backend/db/persister.py
> +            session.add(dbPeriod)
Done in `src/backend/business/processor.py`.

2023-07-24 06:00 UTC, benoit74 commented on backend/src/backend/business/indicators/content_visit.py
>      def get_dimensions_values(self, input: Input) -> DimensionsValues:
What change should be made to enhance this?

2023-07-24 09:33 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    id: Mapped[int] = mapped_column(init=False, primary_key=True)
I was wrong, we need this. Because the index on the Period table will be a UNIQUE INDEX, while the one on Record/State tables will be a regular INDEX. And this means a significant difference in terms of performances. I kept the table but switched to using the `timestamp` column as PK.

2023-07-24 09:36 UTC, benoit74 commented on backend/src/backend/db/models.py
> +    id: Mapped[int] = mapped_column(init=False, primary_key=True)
NOTA: I decided to keep the `period_id` column name on Record/State tables because I find it makes it way more straightforward that there is a FK to another table + it makes it less weird than having a `timestamp` and a `period` properties on `Record` and `State` classes which leads to the same information.

2023-07-24 10:42 UTC, rgaudin commented on backend/src/backend/business/indicators/content_visit.py
>      def get_dimensions_values(self, input: Input) -> DimensionsValues:
Not ideal but:
```py
def get_dimensions_values(self, input_: Input) -> DimensionsValues:
    ...
```

2023-07-24 11:19 UTC, rgaudin approved these changes
Good!
Please fix the range dependencies and merge

2023-07-24 11:19 UTC, rgaudin commented on backend/pyproject.toml
>      "flake8 >=6.0,<6.1",
Why aren't we using pinned dependencies for the rest??

2023-07-24 14:44 UTC, benoit74 commented on backend/pyproject.toml
>      "flake8 >=6.0,<6.1",
Because this was supposed to be done in https://github.com/offspot/metrics/issues/15, and I didn't wanted to invest time in this now. But I will, ok.

2023-07-24 14:50 UTC, merged

2023-07-24 15:32 UTC, rgaudin commented on backend/pyproject.toml
>      "flake8 >=6.0,<6.1",
Ah sorry I forgot ; you should have merged without it then 😉