Minimal UI
offspot/metrics pull request #58
Opened 2023-12-08 15:05 UTC by benoit74

## Rationale

Fix #46 

## Changes

- add new API endpoint retrieving all KPIs for a given aggregation kind (we need almost all values for main dashboard anyway)
- JSON document attributes (Web API + DB for KPI values) are now camelCase instead of snake_case, as recommended by Google + in line with TS front-end expectations
- migrate the frontend to Typescript instead of Javascript 
- add Vuetify library (and remove Bootstrap + Popper.JS which are not needed anymore)
- implement minimal design of the new UI

2023-12-12 10:10 UTC, rgaudin requested changes
Please update dev/ documentation as it seems outdated. I have errors in multiple containers: instructions for db setup not working anymore, dev frontend not building, 500 error on API… Figured it's be easier to wait for you to fix it 😉

I noticed the logo is an SVG file with odd boundaries (browsers dont treat SVG and bitmap the same regarding to boundaries).
Given this is supposed to reuse the hotspot's style, the Kiwix logo should only be used as fallback. It thus will be a PNG, and provided but you should still handle the fallback of the fallback.

2023-12-12 10:10 UTC, rgaudin commented on frontend/src/views/Home.vue
> +    <v-app-bar flat height="100" style="background-color: rgb(248, 247, 250)">
We don't want inline styles like this I suppose

2023-12-12 10:10 UTC, rgaudin commented on frontend/src/views/Home.vue
> +        <span class="font-weight-bold me-auto">© 2023 Kiwix Association</span>
We don't have this kind of things anywhere else so I'd get rid of it. Also, inviting to get support online is a bit odd given it targets offline mostly.

2023-12-12 10:10 UTC, rgaudin commented on frontend/src/views/Home.vue
> +          <span class="float-left font-weight-black text-h4">Metrics</span>
Shouldn't this be an env-provided variable with the name of the _site/system/hotspot_

2023-12-14 08:52 UTC, benoit74 commented on frontend/index.html
> +    <link rel="stylesheet" type="text/css" href="/loader.css" />
Fixed

2023-12-14 09:01 UTC, benoit74 commented on frontend/src/components/DashboardPackagePopularity.vue
> +  <code>{{ main.getCurrentKpiValue(2001) }}</code>
Done anyway, it's not like it is a big change 🤣

2023-12-14 09:03 UTC, benoit74 commented on frontend/src/components/DashboardSharedFiles.vue
> +  <code>{{ main.getAllKpiValues(2005) }}</code>
Because for this component we will display all values for the selection aggregation kind (i.e. last 7 days, last 4 weeks, ...) while on other component we display only the current value. 

This is a big driver for the backend API design, we need to be able to easily access all KPI values for the selected aggregation because we might want to display all of them.

2023-12-14 09:03 UTC, benoit74 commented on frontend/src/components/DashboardPackagePopularity.vue
> +  font-size: xx-small;
This is just the dirty design, it will disappear soon.

2023-12-14 09:09 UTC, benoit74 commented on frontend/src/stores/main.ts
> +        const data = await axios.get(
Is https://github.com/offspot/metrics/issues/62 in line with what you meant?

2023-12-14 09:09 UTC, rgaudin commented on frontend/src/stores/main.ts
> +        const data = await axios.get(
Yes

2023-12-14 09:19 UTC, benoit74 commented on frontend/src/views/Home.vue
> +        <span class="font-weight-bold me-auto">© 2023 Kiwix Association</span>
I mostly agree, let's note that we need to discuss this with all stakeholders in https://github.com/offspot/metrics/issues/63

2023-12-14 09:25 UTC, benoit74 commented on frontend/src/views/Home.vue
> +          <span class="float-left font-weight-black text-h4">Metrics</span>
Tracked in https://github.com/offspot/metrics/issues/64

2023-12-14 10:05 UTC, benoit74 commented
I've fixed the dev instructions + an issue in the dev frontend-tools container.

I think you've got 500 errors on the API because you are using an old data format, once you will have followed the instruction with the new synthetic dataset, these data will be gone and the API should be ok.

You might also have got issues with kiwix-serve if you did not downloaded the two ZIMs mentioned in the doc (it is not optional if you want kiwix-serve to start).

Everything else should be ok, I've started it locally on a fresh git checkout, let me know if you still experience issues.

2023-12-14 10:06 UTC, benoit74 commented on frontend/index.html
> +    <link rel="stylesheet" type="text/css" href="/loader.css" />
Fixed

2023-12-14 14:07 UTC, rgaudin approved these changes
All good ; thank you for reminding me to rebuild the images. I should enable my brain even when copy/pasting from doc 😅

2023-12-14 14:07 UTC, merged