Add frontend and api
offspot/metrics pull request #6
Opened 2023-07-03 12:35 UTC by benoit74

## Rationale

This is the almost final part of https://github.com/offspot/metrics/issues/1

This should be reviewed after https://github.com/offspot/metrics/pull/4

This PR focuses on :
- the implementation of a system to collect logs and send then to the backend
- the implementation of a UI

## Changes
- add a "test" development environment with a kiwix-server and some static content
- collect Caddy logs with Filebeat and send them to the backend
- implement a first UI + associated backend APIs

2023-07-14 15:31 UTC, rgaudin requested changes
Awaiting backend PR to be merged

2023-09-05 08:48 UTC, benoit74 commented
Finally, this is ready to be reviewed and merged.
The frontend UI is **absolutely not** the final one, but it is a good demo of the system capabilities.

2023-09-06 09:22 UTC, rgaudin requested changes
Thank you. 

I am not commenting on the UI itself as it is understood this is just a way to demonstrate that the data exists and is returned by the API. A message when there is no data returned by the API would be helpful though.

I don't like much how filebeat is handled. process management only when we really have to but I think here we want filebeat to run always and… we're on a docker setup which is a process manager.
Consuming filebeat's log files instead of sucking its output would have less constraint as well.
I think it would be good if you could explain the wanted lifecycle of filebeat and it's various log usage (file and console) so I can understand whether we do have to run it ourselves or if we could defer that to docker and just read its log files (on shm if possible)

2023-09-06 09:22 UTC, rgaudin commented on backend/tests/unit/business/kpis/conftest.py
> +            f"{self.dimension_value0}¶{self.dimension_value1}¶{self.dimension_value2}"
what's this?

2023-09-06 09:22 UTC, rgaudin commented on dev/README.md
> +
You must add where to put them otherwise kiwix-serve wont start

2023-09-07 13:41 UTC, benoit74 commented on backend/Dockerfile
> +ENV ALLOWED_ORIGINS http://localhost:8003|http://127.0.0.1:8003
This is a default value, mostly useful only for dev indeed.
Because some developers tend to prefer one over the other, I used both.
I don't mind to remove this from the image and specify that it is a mandatory environment variable, is it ok for you?

2023-09-07 14:33 UTC, benoit74 commented on backend/filebeat.yml
> +  rotateeverybytes: 1048576 # = 1MB
No, those logs are at a higher level, about the global status of the filebeat process. On a normal basis, some startup information + one line of an internal heartbeat every 30 secs.

2023-09-07 14:34 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/kpis/content_popularity.py
> +        return dumps(
Yes, this is tracked in https://github.com/offspot/metrics/pull/17 (we agreed to do this in a separate issue, and I did not worked on this one yet)

2023-09-07 14:41 UTC, benoit74 commented on backend/src/offspot_metrics_backend/db/initializer.py
> +        os.chdir(src_dir)
Will be done in https://github.com/offspot/metrics/issues/23, this is totally broken anyway.

2023-09-07 14:48 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/period.py
> +    def __init__(self, dt: datetime.datetime) -> None:
Yes, it's the point. But I don't see much difference between __init__ and __post_init__ in this situation, what is your point?

```
    def __init__(self, dt: datetime.datetime) -> None:
        self.dt = datetime.datetime(
            year=dt.year, month=dt.month, day=dt.day, hour=dt.hour
        )
```
vs
```
    def __post_init__(self):
        self.dt = datetime.datetime(
            year=self.dt.year, month=self.dt.month, day=self.dt.day, hour=self.dt.hour
        )
```

2023-09-07 15:22 UTC, rgaudin commented on backend/Dockerfile
> +ENV ALLOWED_ORIGINS http://localhost:8003|http://127.0.0.1:8003
Yes ; actually I'd like us to sort-of standardize the ports and addresses we use on dev as it's a pain to follow with different ones for each project.

Another thing I like to do it to support two origins (I use localhost) on different ports. Allows easy frontend dev by running the compose but solely for the backend and start a separate local yarn to test frontend changes.
➡️ I noticed you fixed that with a dev frontend container with reload that mounts to the codebase. I think we should generalize it. It's cleaner 👍

2023-09-07 15:25 UTC, rgaudin commented on backend/filebeat.yml
> +path.data: /filebeat-data/data
OK 👍

2023-09-07 15:27 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/kpis/content_popularity.py
> +        return dumps(
OK then

2023-09-07 15:56 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/period.py
> +    def __init__(self, dt: datetime.datetime) -> None:
It's just about semantics. `__post_init__` implies that you're transforming passed values but dataclass behavior is untouched. `__init__` requires more attention. 

```py
def __post_init__(self):
    self.dt = datetime.datetime.combine(self.dt.date(), datetime.time(self.dt.hour))
```

2023-09-08 06:51 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/period.py
> +            ) + datetime.timedelta(days=1 - self.weekday)
I don't mind, I've switch to your preference

2023-09-08 07:03 UTC, benoit74 commented on backend/src/offspot_metrics_backend/main.py
> +                system_exit = SystemExit("Processor is not set")
Replaced by a `sys.exit("Processor is not set")`

2023-09-08 07:06 UTC, benoit74 commented on backend/src/offspot_metrics_backend/main.py
> +            await sleep(60)
I replaced it by a named constant. Replacing it by an environment variable is not negligible, at least some impact analysis should be done, I'm not sure we can do it easily.

2023-09-08 07:08 UTC, benoit74 commented on backend/src/offspot_metrics_backend/filebeat.py
> +                    logger.debug(f"Filebeat sent: {line}")
I suppose we will get rid of this once https://github.com/offspot/metrics/issues/20 is implemented.

2023-09-08 07:10 UTC, benoit74 commented on backend/src/offspot_metrics_backend/filebeat.py
> +                    await sleep(10)
Why not? What would be your proposition? The idea was to not start it in a fast loop (every second) but not to wait too long (one minute) and I settle on 10 secs, but could be anything else.

2023-09-08 07:14 UTC, benoit74 commented on dev/docker-compose.yml
> +    image: ghcr.io/kiwix/kiwix-serve
You mean that offspot doesn't have a `latest` / `dev` tag on kiwix-serve, right? (`dev` is still present but I assume it is not maintained anymore, since not present in the github workflow, right ?)

2023-09-08 07:17 UTC, benoit74 commented on dev/packages.orig.yml
> +---
This is the whole file you gave me, for reference.
I would prefer to replace it with a link to the official reference documentation on `packages.yml` format but failed to find it in `offspot` repos, did I missed it?

2023-09-08 07:19 UTC, benoit74 commented on dev/reverse-proxy/config/Caddyfile
> +            roll_size 1MiB
Nope, this is a sensible setting for a dev environment. 
I have no idea (yet) regarding what should be done in the real offspot.

2023-09-08 07:24 UTC, benoit74 commented on dev/reverse-proxy/data/.gitignore
> +# Ignore everything in this directory
I don't have any idea of what this is. Let remove this, it will be easy to add back once we know it is need. This is the problem with reviewing code that has been written more than one month ago ...

2023-09-08 07:27 UTC, benoit74 commented on frontend/.gitignore
> +# Logs
I just removed it, most was already covered by the top .gitignore, and what is not covered is probably useless in a Dockerized environment, or should be added to the top .gitignore

2023-09-08 07:48 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
I don't understand, what should I change to use faster C-extension version? (I'm sorry but PyYaml documentation is ... limited at best, at least the one I found)

2023-09-08 08:01 UTC, rgaudin commented on dev/docker-compose.yml
> +    image: ghcr.io/kiwix/kiwix-serve
That's right.

2023-09-08 08:08 UTC, rgaudin commented on dev/packages.orig.yml
> +---
There's no sample indeed. There's only documentation in the README.
What I don't link about samples is that we have to maintain them.
I'm afraid upstream will change the format and we'll have this become obsolete. A _working_ example is needed but your already have some in the repo. This file doesn't have any more value but we can keep it if you think it's useful

2023-09-08 08:09 UTC, rgaudin commented on dev/reverse-proxy/config/Caddyfile
> +            roll_size 1MiB
OK

2023-09-08 08:13 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
pyyaml has both a pure-python implementation and a cython extension one which is faster but obviously less versatile. Which one you use is based on imports

See https://github.com/offspot/offspot-config/blob/main/src/offspot_config/utils/yaml.py#L6

2023-09-08 08:28 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +        match = re.match(r"^//(.*?)/.*", url)
Done in `architecture_technical.md`, in the `Integration` section where I already placed other assumptions like this one.

2023-09-08 08:57 UTC, benoit74 commented on dev/docker-compose.yml
> +    image: ghcr.io/kiwix/kiwix-serve
Tracked as https://github.com/offspot/metrics/issues/24, this was not straightforward at all.

2023-09-08 09:05 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            self.warnings.append(f"Package with unsupported 'kind' : '{kind}' ignored")
Yes, apps are not covered by current code, and edupi will have to be integrated rather soon 😄

2023-09-08 09:07 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +        """Transform one log line into corresponding inputs"""
Nope, those are not filebeat logs (see previous comment regarding the content of filebeat logs), they are logs found by filebeat, coming from Caddy indeed

2023-09-08 09:09 UTC, benoit74 commented on backend/src/offspot_metrics_backend/routes/kpis.py
> +            "description": "Returns the kpi value for a given aggregation",
Yes, see comment below.

2023-09-08 09:11 UTC, benoit74 commented on backend/src/offspot_metrics_backend/routes/kpis.py
> +    agg_kind: str,
They are query parameters. Is there any way to be more explicit about it with FastAPI? (documentation is not speaking about it in the dedicated page at https://fastapi.tiangolo.com/tutorial/query-params/)

2023-09-08 09:17 UTC, benoit74 commented on backend/tests/unit/business/kpis/conftest.py
> +            f"{self.dimension_value0}¶{self.dimension_value1}¶{self.dimension_value2}"
something which should probably be replaced by a tuple? (this is what I did at least)

2023-09-08 09:21 UTC, benoit74 commented on dev/docker-compose.yml
> +      - ../backend/src/offspot_metrics_backend/dev.db:/data/database.db
Removed / fixed

2023-09-08 09:22 UTC, benoit74 commented on dev/README.md
> +
It is written just above (in the `zims` folder). How can I make it clearer ? (but it is confusing obviously)

2023-09-08 09:29 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +        """Transform one log line into corresponding inputs"""
That's what I understand but the format you're parsing is filebeat specific isn't it? Or a combination of filebeat + Caddy. Maybe a comment below in the parsing code is more appropriate, indeed

2023-09-08 09:30 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
OK, I got it. But using the C-extenstion version means that `LibYAML` must be installed, right? For parsing one small (reasonably at last) yaml file at process startup, I feel that the performance benefit is too limited compared to the installation requirement. Is there any other benefit I missed?

2023-09-08 09:32 UTC, rgaudin commented on dev/README.md
> +
My bad, I didn't see it.

2023-09-08 09:38 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
No, it bundles everything, there's nothing to do except this import gymnastics.
Yet you're right it shouldn't make much of a difference for this files ; hence my question.
Since there's no drawback, there's no reason not to do it.

2023-09-08 09:53 UTC, rgaudin commented on backend/src/offspot_metrics_backend/routes/kpis.py
> +    agg_kind: str,
There's the [`Query`](https://fastapi.tiangolo.com/tutorial/query-params-str-validations) thing that is now optional because fastapi likes implicit. WDYT?

2023-09-08 12:03 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
The drawback is that you cannot `safe_load` with the C-extension, you have to accept the security risk (minimal, I agree) + add the noqa hint
```
conf_data = yaml.load(fh, Loader=CLoader)  # noqa: S506
```

2023-09-08 12:05 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_converter.py
> +            conf_data = yaml.safe_load(stream)
Of course you can `CSafeLoader` is there ; that's actually what's in use in the link I gave you

2023-09-08 12:35 UTC, benoit74 commented on dev/packages.orig.yml
> +---
Which readme? I fail to find it among the offspot repositories, sorry ...

2023-09-08 12:36 UTC, benoit74 commented on dev/docker-compose.yml
> +    image: ghcr.io/kiwix/kiwix-serve
Done indeed.

2023-09-08 12:55 UTC, rgaudin commented on dev/packages.orig.yml
> +---
https://github.com/offspot/offspot-config#offspotyaml-format

2023-09-12 09:18 UTC, benoit74 commented on backend/src/offspot_metrics_backend/filebeat.py
> +                    await sleep(10)
Filebeat has been removed.

2023-09-12 11:47 UTC, rgaudin requested changes
Thank you!

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +            # perform a very small sleep, just to let the coroutine pause
Not sure I understand this comment. `sleep` blocks and the coroutine switches context in-between instructions. `asyncio.sleep` would mean “do something else until this delay expires”. Isn't it? It's what you want to do right?

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        for root, _, files in os.walk(self.watched_folder):
Use `Path`'s rglob instead

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +                # Let consider that all existing files have been modified, so that we
```suggestion
                # Let's consider that all existing files have been modified, so that we
```

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +                # process any line that might have apparead since our last execution
```suggestion
                # process any line that might have appeared since our last execution
```

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        self.file_pointers: dict[str, int] = {}
```suggestion
        self.file_positions_map: dict[str, int] = {}
```

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +            # we should never get there except if something bad happens when modiying
Then is this useful at all? As indicated, it can't be tested.

2023-09-12 11:47 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +                    NewLineEvent(file_path=file_path, line_content=line[:-1])
```suggestion
                    NewLineEvent(file_path=file_path, line_content=line.strip())
```

2023-09-12 13:50 UTC, benoit74 commented on backend/Dockerfile
> + && alembic upgrade head \
The biggest problem is that I did not realized that it means that schema upgrades (e.g. once a new version is released) to an existing database will not be applied.
I didn't wanted to do automatic schema upgrade at application startup because it could become a mess when your application performs the upgrade without you noticing it, but in the case of an "embedded" software like `metrics` where there is no "Ops person" taking care of those schema upgrade, there is no other choice.

2023-09-12 14:58 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/agg_kind.py
> +    def pattern(cls) -> str:
I just added a docstring. It returns a regexp matching enum allowed values.

2023-09-12 15:47 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
> +        with open(BackendConf.package_conf_file_location) as fh:
Fixed, I agree and it makes tests more obvious.

2023-09-12 15:49 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
>          self.files: dict[str, Any] = {}
These functions are called only in `init`. 
I just isolated code in two specific functions to avoid very deeply indented code which is always complex to read. This is also why I added the weak “internal use” indicator "_" in front of function names.

2023-09-12 16:04 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +            # we should never get there except if something bad happens when modiying
I agree that in this situation, it is useless

2023-09-12 16:21 UTC, benoit74 commented
Ready again for review, big change since last review is that DB schema is now always updated at application startup.

2023-09-13 10:16 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        if os.path.getsize(file_path) < self.file_positions_map[str(file_path)]:
It's a `Path` now, you don't have to use `os.path`

2023-09-13 10:18 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        for files in self.watched_folder.rglob("*"):
This also matches folder. is that wanted? Given you know what you're looking for (and that all those files have extensions), you may use `*.*` to filter it.

2023-09-13 10:24 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/reverse_proxy_config.py
> +        self.files: dict[str, Any] = {}
| Cons | Pros |
| --- | --- |
| Someone scanning through `__init__` can't see those properties | ??? |

`__init__` is for object initialization and this is exactly this: initializing properties of this object. There is no condition or anything that would justify not having this in the `__init__`.
Can you tell me why it's so important to initialize those public properties (used externaly by the log parser) in this _private_ method that is called in `__init__` ?

2023-09-13 10:29 UTC, rgaudin commented on backend/tests/unit/conf_files/conf_routes.yaml
> +---
I don't get why this file is named this way

2023-09-13 10:38 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +            # perform a very small sleep, just to let the coroutine pause
My bad, I did not look at the import and now realize you are indeed using `asyncio.sleep`. I'm not used to see `sleep` imported directly 😅

2023-09-13 10:40 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/caddy_log_converter.py
>          self.files: dict[str, Any] = {}
Using another method is fine. I am talking about the initialization of those properties (which would not be indented). See my comment on the new file

2023-09-14 06:52 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        for files in self.watched_folder.rglob("*"):
Good catch. I prefered to test for `file.is_file()`, because of folder could have a dot in its name, and a file could have no dot, even if I agree that log files are supposed to have a dot, but I prefer to be generic at this point.

2023-09-14 06:59 UTC, benoit74 commented on backend/src/offspot_metrics_backend/business/reverse_proxy_config.py
> +        self.files: dict[str, Any] = {}
I finally got your point. Your comment is only about declarations, not about the whole code. Sorry it took me so long to understand (at least I hope I did now 😢)

2023-09-14 08:26 UTC, rgaudin commented on backend/src/offspot_metrics_backend/business/log_watcher.py
> +        for files in self.watched_folder.rglob("*"):
Won't complain about being explicit 😁

2023-09-14 09:23 UTC, merged